name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        environment-file: environment.yml
        activate-environment: base

    - name: Verify installation
      run: |
        conda activate base
        python -m pip --version
        pip list

    - name: Lint with flake8
      run: |
        conda activate base
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda activate base
        pytest

    - name: Build and publish
      if: github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        conda activate base
        python setup.py sdist bdist_wheel
        twine upload dist/*
