name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        auto-update-conda: true

    - name: Debug Conda Installation
      run: |
        conda info
        conda list
        conda update -n base -c defaults conda --yes

    - name: Update Conda Environment
      run: |
        conda env update --file environment.yml --name base --debug || (conda env update --file environment.yml --name base --debug && exit 1)
      env:
        CONDA_NO_PLUGINS: true

    - name: Verify Installation
      run: |
        conda info
        conda list
        conda env list
        conda activate base
